name: dosya_converter
description: Çevrimdışı dosya dönüştürücü (PDF, DOCX, XLSX, PPTX, JPG/PNG, ZIP) + Bulut Entegrasyonları
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


  # 1. PDF İŞLEMLERİ & SAYFA YÖNETİMİ

  pdf: ^3.11.1
  printing: ^5.13.4
  syncfusion_flutter_pdf: ^24.2.7 # PDF birleştirme ve sayfa ayıklama motoru

  # 2. DOSYA SEÇİMİ, ERİŞİMİ & CİHAZ YÖNETİMİ

  file_picker: ^10.3.3
  image_picker: ^1.0.7
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  share_plus: ^10.1.2


  # 3. BELGE & ARŞİV FORMATI İŞLEYİCİLERİ

  archive: ^3.6.1 # ZIP oluşturma ve ayıklama
  excel: ^4.0.6   # XLSX okuma ve işleme
  xml: ^6.5.0     # DOCX / PPTX XML ayrıştırma


  # 4. KİMLİK DOĞRULAMA & BULUT ENTEGRASYONLARI

  # Microsoft Entra ID (Azure AD) & Graph API
  aad_oauth: ^1.0.1

  # Google Sign-In & Google Drive API
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # Ağ / HTTP İstemcisi
  http: ^1.6.0


  # 5. DURUM YÖNETİMİ (STATE MANAGEMENT)

  provider: ^6.1.2

  #6.  Yerel ağ ve QR araçları
  qr_flutter: ^4.1.0
  network_info_plus: ^5.0.1
  # 7. SharedPreferences ayarları
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true